app:
  rabbit:
    host: 192.168.1.7
    exchange_name: fanout.exchange
    active_queue: business-actions-queue
    client_queue: client-actions-queue
spring:
  datasource:
    url: jdbc:postgresql://192.168.1.7:5432/business
    username: manager
    password: pass