app:
  rabbit:
    host: business-rabbit
    exchange_name: fanout.exchange
    active_queue: client-actions-queue
    business_queue: business-actions-queue
spring:
  datasource:
    url: jdbc:postgresql://client-db:5433/client
    username: manager
    password: pass